- set_fact:
    log_config:
      apache_error:
        log_file: "/var/log/apache2/error.log"
        retention: 7
        metric_filters:
          - name: "apache-log-errors"
            pattern: Error
            transformations:
              - name: ApacheErrors
                namespace: WEBHOP
                value: '1'
                default_value: 0

      apache_access:
        log_file: "/var/log/apache2/access.log"
        retention: 1

# register this component with awslogs using the above config
- name: Setup logging for Apache logs
  include: ../../awslogs/tasks/component-setup.yml config=log_config
